# Generated by Django 6.1.1 on 2026-09-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('auther', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('publication', models.CharField(max_length=200)),
            ],
        ),
    ]
