# Generated by Django 6.1.1 on 2026-09-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
